#include "GoBridge.h"
#include <iostream>
#include <dlfcn.h>

// Deep comment: Implementation of GoBridge dynamically linking to the Go `libultra.so`.
// Why: We load the shared library dynamically at runtime rather than statically linking.
//      This allows the UI executables to start even if the Go backend DLL is updating or missing,
//      providing better error handling than an immediate OS-level missing symbol crash.
// Side effects: We must cast `dlsym` results to the exact function signatures generated by CGO.

namespace Core {

// Signatures matching the CGO exports in `go-port/libultra.h`
typedef int (*ExecuteCmdFunc)(const char*);
typedef int (*RegisterListenerFunc)(const char*, NativeEventCallback);
typedef int (*RegisterScintillaFunc)(ScintillaFuncs);

bool GoBridge::Initialize() {
    if (m_initialized) {
        return true;
    }

    std::cout << "[GoBridge] Loading Go Backend Runtime (libultra.so)..." << std::endl;

    // Load the shared library
    m_libHandle = dlopen("./go-port/libultra.so", RTLD_LAZY);
    if (!m_libHandle) {
        std::cerr << "[GoBridge Error] Failed to load libultra.so: " << dlerror() << std::endl;
        return false;
    }

    // Load symbols
    m_execCmdFunc = dlsym(m_libHandle, "ExecuteCommandFromUI");
    m_regListenerFunc = dlsym(m_libHandle, "RegisterNativeEventListener");
    m_regScintillaFunc = dlsym(m_libHandle, "RegisterNativeScintilla");

    if (!m_execCmdFunc || !m_regListenerFunc || !m_regScintillaFunc) {
        std::cerr << "[GoBridge Error] Failed to resolve CGO symbols." << std::endl;
        dlclose(m_libHandle);
        m_libHandle = nullptr;
        return false;
    }

    std::cout << "[GoBridge] Successfully linked Go backend." << std::endl;
    m_initialized = true;
    return true;
}

bool GoBridge::ExecuteCommand(const std::string& commandID, const std::string& jsonPayload) {
    if (!Initialize()) {
        return false;
    }

    std::cout << "[GoBridge] Dispatching Command to Go: " << commandID << std::endl;

    ExecuteCmdFunc execFunc = reinterpret_cast<ExecuteCmdFunc>(m_execCmdFunc);
    int result = execFunc(commandID.c_str());

    return result == 0;
}

bool GoBridge::RegisterEventListener(const std::string& eventID, NativeEventCallback callback) {
    if (!Initialize()) {
        return false;
    }

    std::cout << "[GoBridge] Registering UI Callback for Event: " << eventID << std::endl;

    RegisterListenerFunc regFunc = reinterpret_cast<RegisterListenerFunc>(m_regListenerFunc);
    int result = regFunc(eventID.c_str(), callback);

    return result == 0;
}

bool GoBridge::RegisterScintilla(const ScintillaFuncs& funcs) {
    if (!Initialize()) {
        return false;
    }

    std::cout << "[GoBridge] Registering Native C++ Scintilla callbacks with Go backend." << std::endl;

    RegisterScintillaFunc regFunc = reinterpret_cast<RegisterScintillaFunc>(m_regScintillaFunc);
    int result = regFunc(funcs);

    return result == 0;
}

GoBridge::~GoBridge() {
    if (m_libHandle) {
        dlclose(m_libHandle);
    }
}

} // namespace Core
